---
- name: Install Apache
  apt:
    name: apache2
    state: present
    update_cache: yes
  tags: apache

- name: Copy custom index.html from template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Restart Apache
  when: env == "staging"
  tags: apache

- name: Ensure Apache is started and enabled
  service:
    name: apache2
    state: started
    enabled: yes
  tags: apache
